### ISSUE TITLE
[要望] Gulpとプロジェクト構成

### ISSUE THREAD

**Issue by ghost** [inubushiC4M/wg-susume#1]

**Comment by ghost** [comment]
/src/css/top.css
はどういう扱いのファイル？

・本来/dist/にあるものだが間違えて置いてしまった
・Gulpタスクが意図しない挙動となっていて出力されている
等の原因が考えられるかと思われます。

ゴミファイルであれば削除、Gulpの処理の見直しを提案。

**Comment by inubushiC4M** [comment]
/src/css/top.css　は
ご指摘の通り意図しない動きでしたので
Gulpの処理の見直しを行いました。

**Comment by ghost** [comment]
/src/css/top.css
が残存しているようです。
「src」にあるべきソースファイルではないのであれば削除しておきましょう。

**Comment by ghost** [comment]
修正確認
